/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Alertas;

import Financas.controller.ctr_Caixa;
import Financas.controller.ctr_Centrocusto;
import Financas.controller.ctr_Recibo;
import java.sql.Connection;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import static Financas.view.formGerenciarRecibos.setarTotais;
import static Financas.view.formGerenciarRecibos.updateRecibos;

/**
 *
 * @author El Router
 */
public class frmAlertaExcluzao extends javax.swing.JFrame {

    /**
     * Creates new form frmAlerta
     */
    private ctr_Caixa controller;
    private ctr_Recibo c_recibos;
    private ctr_Centrocusto c_centro;
    private Connection conn;
    String info;
    int codigoEliminar;
    private String tabela;
    private int id;
    private DecimalFormat df;

    public frmAlertaExcluzao(Connection con, String sm1, String sm2, String sm3, String informacao, String tabela) {
        initComponents();
        this.info = informacao;
        this.tabela = tabela;
        this.id = Integer.parseInt(sm3);
        this.conn = con;
        controller = new ctr_Caixa(conn);
        c_centro = new ctr_Centrocusto(conn);
//        System.out.println("sm1" + sm1 + "sm2" + sm2 + "sm3" + sm3);
        jLabelMensagem.setText(
                "<html><font color = \"#000000\"> <left> " + sm1 + "<br>" + "Código:" + sm2 + "  " + sm3 + "<br> </br></html> "
        );
    }

    public frmAlertaExcluzao(Connection con, String alerta, String numero, String titulo, String valor, String tabela, String a) {
        initComponents();
        this.info = alerta;
        this.tabela = tabela;
        this.id = Integer.parseInt(numero);
        this.conn = con;
        df = new DecimalFormat("#,##0.00");
        controller = new ctr_Caixa(conn);
        c_recibos = new ctr_Recibo(conn);
        jLabelMensagem.setText(
                "<html><font color = \"#000000\"> <left> " + alerta + "<br><br>" + " Número: " + numero + " Titulo :  " + titulo + "  Valor " + valor + " <br> </br></html> "
        );
    }

    public frmAlertaExcluzao(Connection con, String sm1, String sm2, String sm3, String informacao) {
        initComponents();
        this.info = informacao;
        this.tabela = tabela;
        this.id = Integer.parseInt(sm2);
        this.conn = con;
        controller = new ctr_Caixa(conn);
        System.out.println("sm1" + sm1 + "sm2" + sm2 + "sm3" + sm3);
        jLabelMensagem.setText(
                "<html><font color = \"#000000\"> <left> " + sm1 + "<br>" + "Código:" + sm2 + "  " + sm3 + "<br> </br></html> "
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMensagem = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exclusão");
        setResizable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Sim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Não");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(293, 207));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tabela.equals("caixa")) {
            if (controller.delete(id)) {
                JOptionPane.showMessageDialog(rootPane, "Caixa Eliminado!");
                dispose();
            }
        }
        if (tabela.equals("centro_custo")) {
            if (c_centro.Eliminar(id)) {
                JOptionPane.showMessageDialog(rootPane, "centro_custo Eliminado!");
                dispose();
            }
        }
        if (tabela.equals("recibo")) {
            if (c_recibos.delete(id)) {
                updateRecibos();
                setarTotais();
                dispose();
            }
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Operação Cancelada pelo usuário!");
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAlertaExcluzao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAlertaExcluzao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAlertaExcluzao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAlertaExcluzao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmAlerta().setVisible(true);
//            }
//        });
        //</editor-fold>
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmAlerta().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
