/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLINICA.view;

import CLINICA.controller.ControllerUsuario;
import CLINICA.controller.ControllerUtente;
import CLINICA.controller.ControllerFormaPagamento;
import CLINICA.controller.ControllerSeguradora;
import CLINICA.controller.ControllerFacturaItens;
import CLINICA.excell.AbrilExcell;
import CLINICA.relatorios.RelatorioFinanceiro;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import sf.ce.conexao.ConexaoBancos;

/**
 *
 * @author Probook
 */
public class MovimentoCaixa extends javax.swing.JFrame {

    /**
     * Creates new form MovimentoCaixa
     */
    ControllerUsuario controllerUsuario;
    ControllerFormaPagamento controllerFormaPagamento;
    ControllerUtente controllerUtente;
    ControllerSeguradora controllerSeguradora;
    ControllerFacturaItens controllerFacturaItens;
    Connection con;
    int codigoTipoUtilizador;
    int valorNumerario = 0, valorSeguradora = 0, valorTransferencia = 0, valorMulticaixa = 0;

    public MovimentoCaixa(int codigo) {
        initComponents();
        con = new ConexaoBancos().ConexaoBD();
        jDateChooser1.setDate(new Date());
        jDateChooser2.setDate(new Date());
        controllerFacturaItens = new ControllerFacturaItens(con);
        controllerSeguradora = new ControllerSeguradora(con);
        controllerFormaPagamento = new ControllerFormaPagamento(con);
        controllerUsuario = new ControllerUsuario(con);
        controllerUtente = new ControllerUtente(con);
        codigoTipoUtilizador = controllerUsuario.getTipoUtilizadorporID(codigo);
        jComboBox1.setModel(new DefaultComboBoxModel(controllerUsuario.getUsernameRecepcao().toArray()));
        jComboBox1.addItem("TODOS");
        jComboBox2.setModel(new DefaultComboBoxModel(controllerFormaPagamento.getDesignacaoFormaPagamento().toArray()));
        jComboBox2.addItem("TODOS");
        // jComboBox3.setModel(new DefaultComboBoxModel(controllerSeguradora.getTodasSeguradoras().toArray()));
        jComboBox3.addItem("TODOS");
        setLocationRelativeTo(null);

        iconeSistema();
    }

    public final void iconeSistema() {
        // URL caminho = this.getClass().getResource("/meus icons/GRest.png");
        URL caminho = this.getClass().getResource("/sf/ce/imagens/Icons/logoteste2.jpg");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminho);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Movimento");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Movimento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel2.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel3.setText("Data 1:");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel4.setText("Data 2:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel5.setText("Tipo de Movimento:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/icons8-microsoft-excel-32.png"))); // NOI18N
        jButton1.setText(" Excell");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/icons8-pdf-32 (2).png"))); // NOI18N
        jButton3.setText("Lista");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(14, 14, 14))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jRadioButton1.setText("Sintetico");
        jRadioButton1.setEnabled(false);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Detalhado");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jRadioButton3.setText("Por Categoria");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jRadioButton4.setText("Por Nome do Paciente");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(32, 32, 32)
                .addComponent(jRadioButton3)
                .addGap(29, 29, 29)
                .addComponent(jRadioButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escolha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 11))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel6.setText("Entidade:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    public String getDate1() {
        String dataSelecionada = "2015-03-07";

        if (jDateChooser1.getDate() != null) {
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTime(jDateChooser1.getDate());
            dataSelecionada = gc.get(GregorianCalendar.YEAR) + "-"
                    + (gc.get(GregorianCalendar.MONTH) + 1) + "-"
                    + gc.get(GregorianCalendar.DATE);
        }
        return dataSelecionada;
    }

    public String getDate2() {
        String dataSelecionada = "2015-03-07";

        if (jDateChooser2.getDate() != null) {
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTime(jDateChooser2.getDate());
            dataSelecionada = gc.get(GregorianCalendar.YEAR) + "-"
                    + (gc.get(GregorianCalendar.MONTH) + 1) + "-"
                    + gc.get(GregorianCalendar.DATE);
        }
        return dataSelecionada;
    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (codigoTipoUtilizador == 4 || codigoTipoUtilizador == 9) {
            if (jRadioButton1.isSelected()) {
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    valorNumerario = valorNumerario + controllerFacturaItens.getValorTotalNumerario(getDate1(), getDate1());
                    valorMulticaixa = valorMulticaixa + controllerFacturaItens.getValorTotalMulticaixa(getDate1(), getDate1());
                    valorTransferencia = valorTransferencia + controllerFacturaItens.getValorTotalTransferencia(getDate1(), getDate1());
                    valorSeguradora = valorSeguradora + controllerFacturaItens.getValorSeguradora(getDate1(), getDate1());
                    System.out.println("Numerario:" + valorNumerario);
                    System.out.println("Multicaixa:" + valorMulticaixa);
                    System.out.println("Transferencia:" + valorMulticaixa);
                    System.out.println("Seguradora:" + valorSeguradora);
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioSintetico(getDate1(), getDate1(), valorNumerario, valorMulticaixa, valorTransferencia, valorSeguradora);
                }
            }
            if (jRadioButton2.isSelected()) {
                if (!jComboBox1.getSelectedItem().equals("TODOS") && !jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    int codigoUser = controllerUsuario.getCodigoUtilizadorUsername(jComboBox1.getSelectedItem().toString());
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatoriosSinteticoporForma(getDate1(), getDate1(), codigoUser, jComboBox2.getSelectedItem().toString());
                }
                if (!jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    int codigoUser = controllerUsuario.getCodigoUtilizadorUsername(jComboBox1.getSelectedItem().toString());
                    relatorioFinanceiro.lrelatorioDetalhadoUser(getDate1(), getDate1(), codigoUser);
                }
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && !jComboBox3.getSelectedItem().equals("TODOS")) {
                    if (jComboBox3.getSelectedItem().equals("PARTICULAR")) {
                        RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                        relatorioFinanceiro.lrelatorioDetalhadoParticular(getDate1(), getDate1());
                    }

                }
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodos(getDate1(), getDate1());

                }
            }
            if (jRadioButton3.isSelected()) {
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodosporCategoria(getDate1(), getDate1());

                }
            }
            if (jRadioButton3.isSelected()) {
                if (!jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    int codigoUser = controllerUsuario.getCodigoUtilizadorUsername(jComboBox1.getSelectedItem().toString());
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodosporCategoria1(getDate1(), getDate1(), codigoUser);

                }
            }
            if (jRadioButton4.isSelected()) {
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodosporPorPaciente(getDate1(), getDate1());

                }
            }
        } else {
            if (jRadioButton1.isSelected()) {
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    valorNumerario = valorNumerario + controllerFacturaItens.getValorTotalNumerario(getDate1(), getDate2());
                    valorMulticaixa = valorMulticaixa + controllerFacturaItens.getValorTotalMulticaixa(getDate1(), getDate2());
                    valorTransferencia = valorTransferencia + controllerFacturaItens.getValorTotalTransferencia(getDate1(), getDate2());
                    valorSeguradora = valorSeguradora + controllerFacturaItens.getValorSeguradora(getDate1(), getDate2());
                    System.out.println("Numerario:" + valorNumerario);
                    System.out.println("Multicaixa:" + valorMulticaixa);
                    System.out.println("Transferencia:" + valorMulticaixa);
                    System.out.println("Seguradora:" + valorSeguradora);
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioSintetico(getDate1(), getDate2(), valorNumerario, valorMulticaixa, valorTransferencia, valorSeguradora);
                }
            }
            if (jRadioButton2.isSelected()) {
                if (!jComboBox1.getSelectedItem().equals("TODOS") && !jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    int codigoUser = controllerUsuario.getCodigoUtilizadorUsername(jComboBox1.getSelectedItem().toString());
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatoriosSinteticoporForma(getDate1(), getDate2(), codigoUser, jComboBox2.getSelectedItem().toString());
                }
                if (!jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    int codigoUser = controllerUsuario.getCodigoUtilizadorUsername(jComboBox1.getSelectedItem().toString());
                    relatorioFinanceiro.lrelatorioDetalhadoUser(getDate1(), getDate2(), codigoUser);
                }
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && !jComboBox3.getSelectedItem().equals("TODOS")) {
                    if (jComboBox3.getSelectedItem().equals("PARTICULAR")) {
                        RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                        relatorioFinanceiro.lrelatorioDetalhadoParticular(getDate1(), getDate2());
                    }

                }
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodos(getDate1(), getDate2());

                }
            }
            if (jRadioButton3.isSelected()) {
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodosporCategoria(getDate1(), getDate2());

                }
            }
            if (jRadioButton4.isSelected()) {
                if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodosporPorPaciente(getDate1(), getDate2());

                }
            }
             if (jRadioButton3.isSelected()) {
                if (!jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                    int codigoUser = controllerUsuario.getCodigoUtilizadorUsername(jComboBox1.getSelectedItem().toString());
                    RelatorioFinanceiro relatorioFinanceiro = new RelatorioFinanceiro();
                    relatorioFinanceiro.lrelatorioDetalhadoTodosporCategoria1(getDate1(), getDate2(), codigoUser);

                }
            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jRadioButton1.isSelected()) {
            if (jComboBox1.getSelectedItem().equals("TODOS") && jComboBox2.getSelectedItem().equals("TODOS") && jComboBox3.getSelectedItem().equals("TODOS")) {
                AbrilExcell abrilExcell = new AbrilExcell();
                abrilExcell.MovimentoSintetico(getDate1(), getDate2());
                JOptionPane.showMessageDialog(null, "Folha de Movimentpo em Excell gerado com Sucesso.");
            } else {
                JOptionPane.showMessageDialog(null, "Todos as opções deve estar selecionado para Todos. Obrigado!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não é permitido, por favor verificado o tipo de Movimento");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimentoCaixa(1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
