/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CLINICA.view;

import CLINICA.controller.ControllerEcografia;
import CLINICA.modelo.ResultadoRaioX;
import CLINICA.controller.ControllerPedidoRaioX;
import CLINICA.controller.ControllerResultadoRaioX;
import CLINICA.controller.ControllerUsuario;
import CLINICA.controller.ControllerUtente;
import CLINICA.controller.ControllerServico;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import sf.ce.conexao.ConexaoBancos;
import sf.ce.utilizacoes.Data;

/**
 *
 * @author Probook
 */
public class ResultadoEcografia extends javax.swing.JFrame {

    /**
     * Creates new form ResultadoRaixo
     */
    PreparedStatement ps;
    ResultSet rs;
    String foto;
    String nomeProduto;
    Connection con;
    Data d = new Data();
    ControllerUtente controllerUtente;
    ControllerUsuario controllerUsuario;
    ControllerPedidoRaioX controllerPedidoRaioX;
    ControllerServico controllerServico;
    ControllerResultadoRaioX controllerResultadoRaioX;
    ResultadoRaioX resultadoRaioX = new ResultadoRaioX();
    ControllerEcografia controllerEcografia;
    ControllerUtente controllerBeneficiario;
    int codigoUser;
    String foto1;
    String bkpfile;
    String bkppath;

    public ResultadoEcografia(int codigo) {

        initComponents();
        this.codigoUser = codigo;
        jDateChooser1.setDate(new Date());
        jDateChooser2.setDate(new Date());
        controllerUtente = new ControllerUtente(con);
        controllerServico = new ControllerServico(con);
        controllerBeneficiario = new ControllerUtente(con);
        controllerPedidoRaioX = new ControllerPedidoRaioX(con);
        controllerResultadoRaioX = new ControllerResultadoRaioX(con);
        controllerEcografia = new ControllerEcografia(con);
        mostrarExame("SELECT p.idPedido as codigo,pa.nomeCompleto as nome,s.designacao as ecografia, p.dataPedido as data, p.estado as estado,p.colaborador as colaborador FROM pedidoecografia p inner join pedidos_ecografia p1 on p.idPedido =p1.codigoPedido\n"
                + "inner join servicos s on s.idServico = p1.codigoServico inner join pacientes pa\n"
                + "on pa.idPaciente = p.codigoPaciente\n"
                + "where  p1.estado='Nao' AND p1.dataPedido =current_date order by p.dataPedido");
        // date(f.datafactura)
        setLocationRelativeTo(null);
        iconeSistema();
    }

    public final void iconeSistema() {
        // URL caminho = this.getClass().getResource("/meus icons/GRest.png");
        URL caminho = this.getClass().getResource("/sf/ce/imagens/Icons/logoteste2.jpg");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(caminho);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fotoLB = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Ecografia");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Designação", "Data", "Atendido", "Colaborador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Ecografia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 3, 11))); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/icons8-add-database-32.png"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jEditorPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Prescrição da Ecografia"));
        jScrollPane2.setViewportView(jEditorPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/iconfinder_multimedia-49_2849787 (2).png"))); // NOI18N
        jButton1.setText("Imagem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/iconfinder_multimedia-22_2849814.png"))); // NOI18N
        jButton2.setText("Audio");
        jButton2.setEnabled(false);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/iconfinder_multimedia-37_2849799.png"))); // NOI18N
        jButton3.setText("Video");
        jButton3.setEnabled(false);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/icons8-save-as-filled-32.png"))); // NOI18N
        jButton5.setText("Revisão");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/icons8-binder-32.png"))); // NOI18N
        jButton6.setText("Arquivar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sf/ce/imagens/Icons/icons8-exit-sign-32 (1).png"))); // NOI18N
        jButton7.setText("Cancelar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Imagem da Ecografia"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoLB, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Modelos"));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Ecografia Pelvica");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Ecografia Morfologica");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("Ecografia Obstétrica");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setSelected(true);
        jRadioButton6.setText("Nenhuma das Opções");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("Outros");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(702, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton2))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jRadioButton5)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Paciente");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Ecografia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1047, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 635, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Date getData() {
        return d.converteDataSql(jDateChooser1.getDate());
    }

    public Date getData1() {
        return d.converteDataSql(jDateChooser2.getDate());
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarImagem();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String codigo = jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        if (!jRadioButton6.isSelected()) {
            jLabel1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jLabel2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            int idade = controllerBeneficiario.getIdade(jLabel2.getText());
            //   int codigoProduto = controllerServico.getCodigoServicoprLike(jRadioButton2.getText());
            if (jRadioButton2.isSelected()) {
                int resposta = JOptionPane.showConfirmDialog(null, "Ecografia Pélvica", "Atenção", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    String dados = "Ecografia Pelvica";
                    dados = jLabel1.getText();
                    int codigoProduto = controllerServico.getCodigoServico(dados);
                    System.out.println("Codigo:" + codigoProduto);
                    String resultado = controllerEcografia.getDesignacao(codigoProduto);
                    String ovario = controllerEcografia.getOvario(codigoProduto);
                    String conclusao = controllerEcografia.getConclusao(codigoProduto);
                    new ProcessarEcografia(jLabel2.getText(), idade, jRadioButton2.getText(), resultado, ovario, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                } else if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica segundo e terceiro trimestre?", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Obstétrica segundo e terceiro trimestre";
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        //  String ovario = controllerEcografia.getOvario(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                    }
                } 
                if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica primeiro trimestro", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Obstétrica primeiro trimestro";
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        //  String ovario = controllerEcografia.getOvario(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                    }
                }
                if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica Gemelar", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Obstétrica Gemelar";
                        //   dados = jLabel1.getText();
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        //  String ovario = controllerEcografia.getOvario(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                    }
                }

            }
            if (jRadioButton5.isSelected()) {

                int resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica segundo e terceiro trimestre?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    String dados = "Ecografia Obstétrica segundo e terceiro trimestre";
                    dados = jLabel1.getText();
                    int codigoProduto = controllerServico.getCodigoServico(dados);
                    String resultado = controllerEcografia.getDesignacao(codigoProduto);
                    //  String ovario = controllerEcografia.getOvario(codigoProduto);
                    String conclusao = controllerEcografia.getConclusao(codigoProduto);
                    new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                } else if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica primeiro trimestro", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Obstétrica primeiro trimestro";
                        dados = jLabel1.getText();
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        //  String ovario = controllerEcografia.getOvario(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                    }
                } 
                if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Obstétrica";
                        dados = jLabel1.getText();
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        //  String ovario = controllerEcografia.getOvario(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                    }
                }
                if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Obstétrica Gemelar", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Obstétrica Gemelar";
                        //   dados = jLabel1.getText();
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        //  String ovario = controllerEcografia.getOvario(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarAbdominal(jLabel2.getText(), idade, dados, resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
                    }
                }

            }
            if (jRadioButton3.isSelected()) {
                int resposta = JOptionPane.showConfirmDialog(null, "Ecografia Morfologica do primeiro trimestre?", "Atenção", JOptionPane.YES_NO_OPTION);
                if (resposta == JOptionPane.YES_OPTION) {
                    String dados = "Ecografia Morfologica do primeiro trimestre";
                    dados = jLabel1.getText();
                    int codigoProduto = controllerServico.getCodigoServico(dados);
                    String resultado = controllerEcografia.getDesignacao(codigoProduto);
                    String conclusao = controllerEcografia.getConclusao(codigoProduto);
                    new ProcessarMorfologica(jLabel2.getText(), idade, dados, codigoProduto, codigo).setVisible(true);

                } else if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Morfologica do segundo trimestre", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Morfologica do segundo trimestre";
                        dados = jLabel1.getText();
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarMorfologica(jLabel2.getText(), idade, dados, codigoProduto, codigo).setVisible(true);
                    }
                }
                if (resposta == JOptionPane.NO_OPTION) {
                    resposta = JOptionPane.showConfirmDialog(null, "Ecografia Morfologica", "Atenção", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) {
                        String dados = "Ecografia Morfologica";
                        dados = jLabel1.getText();
                        int codigoProduto = controllerServico.getCodigoServico(dados);
                        String resultado = controllerEcografia.getDesignacao(codigoProduto);
                        String conclusao = controllerEcografia.getConclusao(codigoProduto);
                        new ProcessarMorfologica(jLabel2.getText(), idade, dados, codigoProduto, codigo).setVisible(true);
                    }
                }

            }
            if (jRadioButton7.isSelected()) {
                int codigoProduto = controllerServico.getCodigoServico(jRadioButton7.getText());
                String resultado = controllerEcografia.getDesignacao(codigoProduto);
                String ovario = controllerEcografia.getOvario(codigoProduto);
                String conclusao = controllerEcografia.getConclusao(codigoProduto);
                new ProcessarAbdominal(jLabel2.getText(), idade, jLabel1.getText(), resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
            }
        } else {
            jLabel1.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            jLabel2.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
            int idade = controllerBeneficiario.getIdade(jLabel2.getText());
            int codigoProduto = controllerServico.getCodigoServico(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
            if (jLabel1.getText().equals("Ecografia Pelvica")) {
                String resultado = controllerEcografia.getDesignacao(codigoProduto);
                String ovario = controllerEcografia.getOvario(codigoProduto);
                String conclusao = controllerEcografia.getConclusao(codigoProduto);
                new ProcessarEcografia(jLabel2.getText(), idade, jLabel1.getText(), resultado, ovario, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
            } else if ((jLabel1.getText().equals("Ecografia Abdominal")) || (jLabel1.getText().equals("Ecografia Obstétrica"))) {
                String resultado = controllerEcografia.getDesignacao(codigoProduto);
                String conclusao = controllerEcografia.getConclusao(codigoProduto);

                new ProcessarAbdominal(jLabel2.getText(), idade, jLabel1.getText(), resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
            } else if ((jLabel1.getText().equals("Ecografia da Mama")) || (jLabel1.getText().equals("Ecografia da Tiroide")) || (jLabel1.getText().equals("Ecografia da Testicular"))) {
                String resultado = controllerEcografia.getDesignacao(codigoProduto);
                String ovario = controllerEcografia.getOvario(codigoProduto);
                String conclusao = controllerEcografia.getConclusao(codigoProduto);
                new ProcessarAbdominal(jLabel2.getText(), idade, jLabel1.getText(), resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
            } else if ((jLabel1.getText().equals("Ecografia Morfologica"))) {
                String resultado = controllerEcografia.getDesignacao(codigoProduto);
                String conclusao = controllerEcografia.getConclusao(codigoProduto);
                new ProcessarMorfologica(jLabel2.getText(), idade, jLabel1.getText(), codigoProduto, codigo).setVisible(true);
            } else {
                String resultado = controllerEcografia.getDesignacao(codigoProduto);
                String ovario = controllerEcografia.getOvario(codigoProduto);
                String conclusao = controllerEcografia.getConclusao(codigoProduto);
                new ProcessarAbdominal(jLabel2.getText(), idade, jLabel1.getText(), resultado, conclusao, codigoUser, codigoProduto, codigo).setVisible(true);
            }
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        salvar();
        controllerPedidoRaioX.updateRaioX(Integer.parseInt(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString()));
        JOptionPane.showMessageDialog(null, "Imagem arquivado com Sucesso");
        mostrarExame("select f.codigoCliente as codigo, f.nomeClientes as nome,s.designacao as ecografia,date(f.datafactura) as data,m.Atendido as estado from factura f inner join factura_itens  f1 on f.idfactura = f1.codigoFactura\n"
                + "inner join servicos s on f1.codigoProduto = s.idServico\n"
                + "inner join marcacaoconsulta m on m.codigoPaciente = f.codigoCliente\n"
                + "WHERE date(f. dataFactura) = current_date and f1.codigoCategoria =5");
        limpar();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        mostrarExame("SELECT p.idPedido as codigo,pa.nomeCompleto as nome,s.designacao as ecografia, p.dataPedido as data, p.estado as estado, p.colaborador as colaborador  FROM pedidoecografia p inner join pedidos_ecografia p1 on p.idPedido =p1.codigoPedido\n"
                + "inner join servicos s on s.idServico = p1.codigoServico inner join pacientes pa\n"
                + "on pa.idPaciente = p.codigoPaciente\n"
                + "where  p1.estado='Nao' AND p1.dataPedido =current_date order by p.dataPedido");
        // date(f.datafactura)        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        mostrarExame("SELECT p.idPedido as codigo,pa.nomeCompleto as nome,s.designacao as ecografia, p.dataPedido as data, p.estado as estado,p.colaborador as colaborador  FROM pedidoecografia p inner join pedidos_ecografia p1 on p.idPedido =p1.codigoPedido\n"
                + "inner join servicos s on s.idServico = p1.codigoServico inner join pacientes pa\n"
                + "on pa.idPaciente = p.codigoPaciente\n"
                + "where p1.estado='Nao' AND date(p1.dataPedido) between '" + getData() + "' and '" + getData1() + "'");
    }//GEN-LAST:event_jButton4ActionPerformed
    public void BuscarImagem() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Buscar Imagem da Ecografia", "wbk");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            bkpfile = chooser.getSelectedFile().getAbsolutePath();
            if (!bkpfile.endsWith(".wbk")) {
                bkpfile += ".wbk";
            }

        }
        File f = chooser.getSelectedFile();
        String filename = f.getPath();
        ImageIcon imageicon = new ImageIcon(filename);
        ImageIcon image = new ImageIcon(filename);
        Image newimg = imageicon.getImage();
        Image newimage = image.getImage();
        Image Editar = newimage.getScaledInstance(fotoLB.getWidth(), fotoLB.getHeight(), Image.SCALE_DEFAULT);
        Image outraimg = newimg.getScaledInstance(fotoLB.getWidth(), fotoLB.getHeight(), Image.SCALE_DEFAULT);
        ImageIcon newicon = new ImageIcon(outraimg);
        ImageIcon novoicon = new ImageIcon(Editar);
        fotoLB.setIcon(newicon);
        foto = filename;
        System.out.println("Teste:" + foto);

    }

    private void recarregarFoto() {
        String modelo = ""; //= empresasController.getLogotipo();

        String filename = modelo;
        ImageIcon imageicon = new ImageIcon(filename);
        ImageIcon image = new ImageIcon(filename);
        Image newimg = imageicon.getImage();
        Image newimage = image.getImage();
        ImageIcon newicon = new ImageIcon(filename);
        fotoLB.setIcon(newicon);

    }

    public void limpar() {
        jEditorPane1.setText("");
        fotoLB.setText("");
    }

    public final void mostrarExame(String sql) {
        System.out.println("Teste:" + sql);
        try {
            con = new ConexaoBancos().ConexaoBD();
            PreparedStatement ps;
            ResultSet rs;
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getTableHeader().setReorderingAllowed(false);
            jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF);
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            model.setNumRows(0);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString("codigo"), rs.getString("nome"), rs.getString("ecografia"), rs.getString("data"), rs.getString("estado"),rs.getString("colaborador")

                });
            }
        } catch (Exception ex) {
            System.out.println("Erro!!!" + ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultadoEcografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultadoEcografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultadoEcografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultadoEcografia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new ResultadoRaixo(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fotoLB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    public String getDescricao() {
        return jEditorPane1.getText();
    }

    public String getNomePaciente() {
        return jLabel2.getText();
    }

    public String getNomeRaiox() {
        return jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString();
    }

    public int getCodigoPaciente() {
        // jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString();
        return controllerUtente.getCodigoUtente(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
    }

    public int getCodigoServico() {
        return controllerServico.getCodigoServico(getNomeRaiox());
    }

    public void salvar() {
        resultadoRaioX.setCodigoPaciente(getCodigoPaciente());
        resultadoRaioX.setCodigoServico(getCodigoServico());
        resultadoRaioX.setCodigoUser(codigoUser);
        resultadoRaioX.setRaioX(getNomeRaiox());
        resultadoRaioX.setDescricao(getDescricao());
        resultadoRaioX.setImagem(foto);
        resultadoRaioX.setSom("");
        resultadoRaioX.setVideo("");
        resultadoRaioX.setNomePaciente(getNomePaciente());
        resultadoRaioX.setEstado("Pronto");
        controllerResultadoRaioX.insertToEcografia(resultadoRaioX);
    }
}
