/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Financas.view;

import Alertas.frmAlertaExcluzao;
import Financas.Relatorios.RelatorioBasico;
import Tabela.Tabla;
import sf.ce.utilizacoes.Data;
import Financas.controller.ctr_Recibo;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JDesktopPane;

/**
 *
 * @author El Router
 */
public class viewGerenciar_recibos extends javax.swing.JInternalFrame {

    private static Tabla t;
    private static Connection conn;
    int rown = -1;
    public static String aux1, aux2, aux3;
    public static double valor = 0;
    public static DecimalFormat df;
    private ctr_Recibo c_recibos;
    private RelatorioBasico report;
    private JDesktopPane desktop;

    public viewGerenciar_recibos(JDesktopPane desktop, Connection conn) {
        initComponents();
        desktop.add(this);
        this.conn = conn;
        report = new RelatorioBasico(conn);
        t = new Tabla(conn);
        c_recibos = new ctr_Recibo(conn);
        df = new DecimalFormat("#,##0.00");
      
    }

   
    public static void updateRecibos() {
        t = new Tabla(conn);
        t.visualizarRecibos(jTableRecibos, 1, "", "");
    }

    public void selectTable() {
        if (jTableRecibos.getRowCount() != 0) {
            jTableRecibos.setRowSelectionInterval(0, 0);
        }
    }

    public static String removerPonto(String num) {
        String novoNumero = "";

        for (int i = 0; i < num.length(); ++i) {
            if (num.charAt(i) == ',') {
                break;
            } else if (num.charAt(i) != '.') {
                novoNumero += num.charAt(i);
            }
        }

        return novoNumero;
    }

    public static void setarTotais() {
        String va4 = "";
        for (int i = 0; i < jTableRecibos.getRowCount(); i++) {
            va4 = "" + jTableRecibos.getValueAt(i, 4);
            aux1 = va4.replaceAll(",00", "");
            aux2 = removerPonto(aux1);
            valor += Double.parseDouble(aux2);
        }
        jTextFieldValor.setText(df.format(valor));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jCheckBoxGeral = new javax.swing.JCheckBox();
        jTextFieldValor = new javax.swing.JTextField();
        jCheckBoxPorData = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserInicial = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jDateChooserFinal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecibos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Pesquisar e Gerenciar RECIBOS");
        setFrameIcon(null);

        jButton2.setText("Buscar Recibo");
        jButton2.setToolTipText("Pesquisar RECIBOS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonAdd.setToolTipText("Adicionar novo RECIBO");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jCheckBoxGeral.setSelected(true);
        jCheckBoxGeral.setText("Pesquisa Geral");
        jCheckBoxGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGeralActionPerformed(evt);
            }
        });

        jTextFieldValor.setEditable(false);
        jTextFieldValor.setBackground(new java.awt.Color(255, 255, 204));
        jTextFieldValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldValor.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldValor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldValor.setText("0,00");
        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });

        jCheckBoxPorData.setText("Pesquisa por Data");
        jCheckBoxPorData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPorDataActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Valor TOTAL");

        jDateChooserInicial.setEnabled(false);

        jButton4.setText("Pesquisar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jDateChooserFinal.setEnabled(false);

        jLabel1.setText("Data Inicial");

        jLabel2.setText("Data Final");

        jTableRecibos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableRecibos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRecibosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRecibos);

        jButton1.setText("Relatório");
        jButton1.setToolTipText(" ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxGeral)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxPorData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldValor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCheckBoxGeral)
                        .addComponent(jCheckBoxPorData))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooserInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButtonAdd)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(150, 50, 743, 549);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        this.setEnabled(false);
//        frmBuscarRecibos hst = new frmBuscarRecibos(this, conn);//2 = Chamada Menu.
        frmBuscarRecibos hst = new frmBuscarRecibos(conn, 1);//2 = Chamada Menu.
        hst.setVisible(true);
//        hst.toFront();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

//        this.setEnabled(false);
//        frmRecibos hst = new frmRecibos(this, conn, 2, 0, "", "", "", "", "","");//2 = Chamada Menu.
//        hst.setVisible(true);
//        hst.toFront();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jCheckBoxGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGeralActionPerformed
        jDateChooserFinal.setEnabled(!true);
        jDateChooserInicial.setEnabled(!true);
    }//GEN-LAST:event_jCheckBoxGeralActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jCheckBoxPorDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPorDataActionPerformed
        jDateChooserFinal.setEnabled(true);
        jDateChooserInicial.setEnabled(true);
        jDateChooserFinal.setDate(new Date());
        jDateChooserInicial.setDate(new Date());
    }//GEN-LAST:event_jCheckBoxPorDataActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        t.visualizarRecibos(jTableRecibos, 2, Data.getData(jDateChooserInicial), Data.getData(jDateChooserFinal));
        setarTotais();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTableRecibosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRecibosMouseClicked
        rown = jTableRecibos.rowAtPoint(evt.getPoint());

        int column = jTableRecibos.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / jTableRecibos.getRowHeight();

        String va1 = "" + jTableRecibos.getValueAt(rown, 0);
        String va2 = "" + jTableRecibos.getValueAt(rown, 1);
        String va3 = "" + jTableRecibos.getValueAt(rown, 2);
        String va4 = "" + jTableRecibos.getValueAt(rown, 3);
        String va5 = "" + jTableRecibos.getValueAt(rown, 4);
        String va6 = "" + jTableRecibos.getValueAt(rown, 5);

        if (evt.getClickCount() == 2) {
            aux1 = va5.replaceAll(",00", "");
            aux2 = removerPonto(aux1);
            valor = Double.parseDouble(aux2);
//            this.setEnabled(false);
            frmRecibos hst = new frmRecibos(conn, 1, valor, c_recibos.getConta(Integer.parseInt(va1)), c_recibos.getCaixa(Integer.parseInt(va1)), va2, va6, aux1, va1);
            hst.setVisible(true);
//            hst.toFront();

        } else {
            if (row < jTableRecibos.getRowCount() && row >= 0 && column < jTableRecibos.getColumnCount() && column >= 0) {
                Object value = jTableRecibos.getValueAt(row, column);
                if (value instanceof JButton) {
                    ((JButton) value).doClick();
                    JButton boton = (JButton) value;

                    if (boton.getName().equals("edit")) {
                        aux1 = va5.replaceAll(",00", "");
                        aux2 = removerPonto(aux1);
                        valor = Double.parseDouble(aux2);
//                        this.setEnabled(false);
                        frmRecibos hst = new frmRecibos(conn, 1, valor, c_recibos.getConta(Integer.parseInt(va1)), c_recibos.getCaixa(Integer.parseInt(va1)), va2, va6, aux1, va1);
                        hst.setVisible(true);
//                        hst.toFront();
                    }
                    if (boton.getName().equals("delete")) {
                        try {
                            new frmAlertaExcluzao(conn, "Deseja realmente excluir esse RECIBO?", va1, va2, va5, "recibo", "").setVisible(true);
                        } catch (Exception ex) {
                            System.out.println(ex.getMessage());
                        }

                    }
                    if (boton.getName().equals("print")) {

                    }
                }
            }
        }

    }//GEN-LAST:event_jTableRecibosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        report.recibosEmitidos();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JCheckBox jCheckBoxGeral;
    private javax.swing.JCheckBox jCheckBoxPorData;
    private com.toedter.calendar.JDateChooser jDateChooserFinal;
    private com.toedter.calendar.JDateChooser jDateChooserInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableRecibos;
    public static javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables

  
}
