/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Financas.view;

import Alertas.frmAlertaExcluzao;
import Tabela.Tabla;
import java.sql.Connection;
import java.text.DecimalFormat;
import javax.swing.JDesktopPane;
import static Financas.view.frmCadastroCaixa.jCheckBoxAbertura;
import static Financas.view.frmCadastroCaixa.jComboBoxTipo;
import static Financas.view.frmCadastroCaixa.jFormattedTextFieldDataAbertura;
import static Financas.view.frmCadastroCaixa.jFormattedTextFieldDataFecho;
import static Financas.view.frmCadastroCaixa.jFormattedTextFieldDataRegistro;
import static Financas.view.frmCadastroCaixa.jTextFieldAgencia;
import static Financas.view.frmCadastroCaixa.jTextFieldContacorrente;
import static Financas.view.frmCadastroCaixa.jTextFieldDescricao;
import static Financas.view.frmCadastroCaixa.jTextFieldGerente;
import static Financas.view.frmCadastroCaixa.jTextFieldID;
import static Financas.view.frmCadastroCaixa.jTextFieldSaldo;
import static Financas.view.frmCadastroCaixa.jTextFieldSaldoInicial;

/**
 *
 * @author El Router
 */
public class viewCaixas extends javax.swing.JInternalFrame {

    /**
     * Creates new form viewCaixas
     */
    private Connection conexao;
    private Tabla t;
    int rown = -1;
    private DecimalFormat decimalformat;
    private DecimalFormat decimalformat2;
    private JDesktopPane desktop;
    
    public viewCaixas(JDesktopPane desktop,Connection conexao) {
        initComponents();
        this.conexao = conexao;
        t = new Tabla(conexao);
        t.visualizarCaixas(jTable1, 1);
        decimalformat = new DecimalFormat("#,##0.00");
        decimalformat2 = new DecimalFormat("####-##-##");
        desktop.add(this);
        selectTable();
    }
    public void selectTable() {
        if (jTable1.getRowCount() != 0) {
            jTable1.setRowSelectionInterval(0, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtPorNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonNovo1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Caixas de Movimentos");
        setAlignmentX(50.0F);
        setAlignmentY(50.0F);
        setFrameIcon(null);
        setPreferredSize(new java.awt.Dimension(900, 480));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton4.setToolTipText("Relatório do Cadastro geral do Livro de CAIXA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ordem de Código", "Ordem de Nome", "Ordenar por Tipo de Cadastro", "Filtrar Caixas CANCELADOS" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de filtro");

        txtPorNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPorNomeCaretUpdate(evt);
            }
        });

        jLabel2.setText("Pesquisa por Nome");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novos/cancelar.png"))); // NOI18N
        jButton5.setToolTipText("Eliminar Registro");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButtonNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novos/add.png"))); // NOI18N
        jButtonNovo1.setText("Cadastrar Novo");
        jButtonNovo1.setBorder(null);
        jButtonNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(150, 50, 858, 563);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //        relatorioCliente.reportClientes();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int index = jComboBox1.getSelectedIndex();
        t.visualizarCaixas(jTable1, index);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtPorNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPorNomeCaretUpdate

    }//GEN-LAST:event_txtPorNomeCaretUpdate

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        rown = jTable1.getSelectedRow();
        int val = Integer.parseInt(jTable1.getValueAt(rown, 0).toString());
        String val2 = "" + jTable1.getValueAt(rown, 1).toString();
        new frmAlertaExcluzao(conexao, "Deseja realmente excluir?", String.valueOf(val), val2, "Exclusao", "caixa").setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        rown = jTable1.getSelectedRow();
        int va1 = Integer.parseInt(jTable1.getValueAt(rown, 0).toString());
        if (evt.getClickCount() == 2) {
//            this.setEnabled(false);
            frmCadastroCaixa icliente = new frmCadastroCaixa();
            icliente.setVisible(true);
//            icliente.toFront();
            getEnviarDados();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    public void getEnviarDados() {

        jTextFieldDescricao.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1).toString());
        jTextFieldID.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0).toString());
        jTextFieldSaldo.setText(decimalformat.format(Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 7).toString())));
        jTextFieldSaldoInicial.setText(decimalformat.format(Double.parseDouble(jTable1.getValueAt(jTable1.getSelectedRow(), 11).toString())));
        jTextFieldAgencia.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4).toString());
        jTextFieldContacorrente.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString());
        jTextFieldGerente.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5).toString());
//        jFormattedTextFieldDataAbertura.setText(decimalformat2.format(jTable1.getValueAt(jTable1.getSelectedRow(), 8).toString()));
        jFormattedTextFieldDataAbertura.setText(decimalformat2.format("20180201"));
//        jFormattedTextFieldDataFecho.setText(decimalformat.format(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString()));
        jFormattedTextFieldDataFecho.setText(decimalformat2.format("20180201"));
//        jFormattedTextFieldDataRegistro.setText(decimalformat.format(jTable1.getValueAt(jTable1.getSelectedRow(), 9).toString()));
        jFormattedTextFieldDataRegistro.setText(decimalformat2.format("20180201"));
        jComboBoxTipo.insertItemAt(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString(), 0);
//        jTextAreaOcorrencia.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString());
        if (jTable1.getValueAt(jTable1.getSelectedRow(), 2).toString().equalsIgnoreCase("BIC")) {
            jCheckBoxAbertura.setSelected(true);
        } else {
            jCheckBoxAbertura.setSelected(false);
        }

    }
    private void jButtonNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovo1ActionPerformed
//        this.setEnabled(false);
//        frmCadastroCaixa icliente = new frmCadastroCaixa(conexao, this, 1);
        frmCadastroCaixa icliente = new frmCadastroCaixa();
        icliente.setVisible(true);
//        icliente.toFront();
    }//GEN-LAST:event_jButtonNovo1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonNovo1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtPorNome;
    // End of variables declaration//GEN-END:variables
}
